/**
 * Runtime build-info reader.
 * Reads dist/build-info.json which is generated by the build script.
 */
import * as fs from "fs";
import * as path from "path";

export function getBuildInfo(): { timestamp: string } | null {
  const buildInfoPath = path.join(__dirname, "build-info.json");
  try {
    const raw = fs.readFileSync(buildInfoPath, "utf8");
    return JSON.parse(raw) as { timestamp: string };
  } catch {
    return null;
  }
}
